// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertDocToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertDocToPDF'](arg1, arg2);
}

export function ConvertHtmlToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertHtmlToPDF'](arg1, arg2);
}

export function ConvertImagesToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertImagesToPDF'](arg1, arg2, arg3);
}

export function ConvertPDFToDocx(arg1, arg2) {
  return window['go']['main']['App']['ConvertPDFToDocx'](arg1, arg2);
}

export function ConvertPDFToHtml(arg1, arg2) {
  return window['go']['main']['App']['ConvertPDFToHtml'](arg1, arg2);
}

export function ConvertPDFToImages(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConvertPDFToImages'](arg1, arg2, arg3, arg4, arg5);
}

export function ConvertPDFToTxt(arg1, arg2) {
  return window['go']['main']['App']['ConvertPDFToTxt'](arg1, arg2);
}

export function ConvertTxtToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertTxtToPDF'](arg1, arg2);
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetPDFPageCount(arg1) {
  return window['go']['main']['App']['GetPDFPageCount'](arg1);
}

export function PreviewImage(arg1) {
  return window['go']['main']['App']['PreviewImage'](arg1);
}

export function PreviewPDFPage(arg1, arg2) {
  return window['go']['main']['App']['PreviewPDFPage'](arg1, arg2);
}

export function SelectDocument(arg1) {
  return window['go']['main']['App']['SelectDocument'](arg1);
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}

export function SelectPDF() {
  return window['go']['main']['App']['SelectPDF']();
}

export function SelectSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3);
}
