// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ConvertDocToPDF(arg1:string,arg2:string):Promise<void>;

export function ConvertHtmlToPDF(arg1:string,arg2:string):Promise<void>;

export function ConvertImagesToPDF(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ConvertPDFToDocx(arg1:string,arg2:string):Promise<void>;

export function ConvertPDFToHtml(arg1:string,arg2:string):Promise<void>;

export function ConvertPDFToImages(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<Array<string>>;

export function ConvertPDFToTxt(arg1:string,arg2:string):Promise<void>;

export function ConvertTxtToPDF(arg1:string,arg2:string):Promise<void>;

export function GetImageInfo(arg1:string):Promise<model.FileInfo>;

export function GetPDFPageCount(arg1:string):Promise<number>;

export function PreviewImage(arg1:string):Promise<string>;

export function PreviewPDFPage(arg1:string,arg2:number):Promise<string>;

export function SelectDocument(arg1:string):Promise<string>;

export function SelectImages():Promise<Array<model.FileInfo>>;

export function SelectOutputDir():Promise<string>;

export function SelectOutputFile():Promise<string>;

export function SelectPDF():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;
